### ISSUE TITLE
Update test all script to cover all versions limitation covered in developers guide

### ISSUE THREAD

**Issue by Grimgoodbye** [GMUCERG/LWC#12]
Currently not all width combinations are covered. Please ensure that all version are covered.

**Comment by kammoh** [comment]
All legal combinations are covered now with `test_all.py` since `f5d563a`. Extra width-compatibility asserts are also added to `LWC`, though I think they might technically be redundant, as the bounds checking is (usually?) performed before the evaluation of asserts. I think they still serve a good job as additional inline documentation, and might actually work under some simulation/synthesis tools (e.g. maybe vivado synth `-assert`?)
